#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"

source "${script_dir}/vars.sh"

SERVICE_VERSION="${SERVICE_VERSION:-local-dev}"

CLOUDSQL_CONNECTION_NAME="${CLOUDSQL_CONNECTION_NAME:-${GCP_PROJECT_ID}:${REGION}:${SQL_INSTANCE_NAME}}"

IMAGE_URI="${IMAGE_URI:-${ARTIFACT_REGISTRY_LOCATION}-docker.pkg.dev/${GCP_PROJECT_ID}/${ARTIFACT_REGISTRY_REPO}/${MAIN_RUN_SERVICE_NAME}:${SERVICE_VERSION}}"

DOCKERFILE_PATH="${DOCKERFILE_PATH:-Dockerfile}"

EXPORTED_READON_AUDIOBOOK_SERVICE_URL="${READON_AUDIOBOOK_SERVICE_URL:-}"
EXPORTED_READON_PHONICS_SERVICE_URL="${READON_PHONICS_SERVICE_URL:-}"
EXPORTED_READON_COMPREHENSION_SERVICE_URL="${READON_COMPREHENSION_SERVICE_URL:-}"
EXPORTED_READON_VISUALIZATION_SERVICE_URL="${READON_VISUALIZATION_SERVICE_URL:-}"
EXPORTED_READON_IMAGE_GENERATION_SERVICE_URL="${READON_IMAGE_GENERATION_SERVICE_URL:-}"
EXPORTED_READON_DASHBOARD_SERVICE_URL="${READON_DASHBOARD_SERVICE_URL:-}"
EXPORTED_DASHBOARD_DATABASE_URL="${DASHBOARD_DATABASE_URL:-}"

set -a
[[ -f "${repo_root}/.env" ]] && source "${repo_root}/.env"
set +a

[[ -n "${EXPORTED_READON_AUDIOBOOK_SERVICE_URL}" ]] && READON_AUDIOBOOK_SERVICE_URL="${EXPORTED_READON_AUDIOBOOK_SERVICE_URL}"
[[ -n "${EXPORTED_READON_PHONICS_SERVICE_URL}" ]] && READON_PHONICS_SERVICE_URL="${EXPORTED_READON_PHONICS_SERVICE_URL}"
[[ -n "${EXPORTED_READON_COMPREHENSION_SERVICE_URL}" ]] && READON_COMPREHENSION_SERVICE_URL="${EXPORTED_READON_COMPREHENSION_SERVICE_URL}"
[[ -n "${EXPORTED_READON_VISUALIZATION_SERVICE_URL}" ]] && READON_VISUALIZATION_SERVICE_URL="${EXPORTED_READON_VISUALIZATION_SERVICE_URL}"
[[ -n "${EXPORTED_READON_IMAGE_GENERATION_SERVICE_URL}" ]] && READON_IMAGE_GENERATION_SERVICE_URL="${EXPORTED_READON_IMAGE_GENERATION_SERVICE_URL}"
[[ -n "${EXPORTED_READON_DASHBOARD_SERVICE_URL}" ]] && READON_DASHBOARD_SERVICE_URL="${EXPORTED_READON_DASHBOARD_SERVICE_URL}"
if [[ -n "${EXPORTED_DASHBOARD_DATABASE_URL}" ]]; then
  DASHBOARD_DATABASE_URL="${EXPORTED_DASHBOARD_DATABASE_URL}"
else
  DASHBOARD_DATABASE_URL=""
fi

READON_IMAGE_GENERATION_SERVICE_URL="${READON_IMAGE_GENERATION_SERVICE_URL:-${READON_VISUALIZATION_SERVICE_URL:-}}"
READON_DASHBOARD_SERVICE_URL="${READON_DASHBOARD_SERVICE_URL:-}"

ENV_VARS="SERVICE_NAME=${MAIN_RUN_SERVICE_NAME}##SERVICE_VERSION=${SERVICE_VERSION}##READON_LOG_LEVEL=${READON_LOG_LEVEL:-info}##READON_DEPLOY_ENV=${READON_DEPLOY_ENV}##CLOUDSQL_CONNECTION_NAME=${CLOUDSQL_CONNECTION_NAME}##CLOUDSQL_INSTANCE_CONNECTION_NAME=${CLOUDSQL_CONNECTION_NAME}##CLOUDSQL_DB_USER=${READON_CLOUDSQL_TCP_USER:-postgres}##CLOUDSQL_DB_PASSWORD=${READON_CLOUDSQL_TCP_PASSWORD:-}##CLOUDSQL_DB_NAME=dashboard##CLOUDSQL_DB_PORT=${READON_CLOUDSQL_TCP_PORT:-5432}##CLOUDSQL_DB_HOST=${READON_CLOUDSQL_TCP_HOST:-127.0.0.1}##READON_READY_REQUIRE_CLOUDSQL_MOUNT=${READON_READY_REQUIRE_CLOUDSQL_MOUNT:-false}##READON_STORAGE_BUCKET=${READON_STORAGE_BUCKET}##READON_DATABASE_NAME=${READON_DATABASE_NAME}##READON_AUDIOBOOK_SERVICE_URL=${READON_AUDIOBOOK_SERVICE_URL:-}##READON_PHONICS_SERVICE_URL=${READON_PHONICS_SERVICE_URL:-}##READON_COMPREHENSION_SERVICE_URL=${READON_COMPREHENSION_SERVICE_URL:-}##READON_VISUALIZATION_SERVICE_URL=${READON_VISUALIZATION_SERVICE_URL:-}##READON_IMAGE_GENERATION_SERVICE_URL=${READON_IMAGE_GENERATION_SERVICE_URL:-}##READON_DASHBOARD_SERVICE_URL=${READON_DASHBOARD_SERVICE_URL:-}##READON_DASHBOARD_HTTP_TIMEOUT_MS=${READON_DASHBOARD_HTTP_TIMEOUT_MS:-15000}##READON_FEATURE_CREDIT_COST=${READON_FEATURE_CREDIT_COST:-10}##READON_AUTH_SECRET=${READON_AUTH_SECRET:-}##READON_AUTH_COOKIE_NAME=${READON_AUTH_COOKIE_NAME:-readon_session}##READON_AUTH_SESSION_TTL=${READON_AUTH_SESSION_TTL:-7d}##READON_DEFAULT_SIGNUP_CREDITS=${READON_DEFAULT_SIGNUP_CREDITS:-100}##DASHBOARD_DATABASE_URL=${DASHBOARD_DATABASE_URL}"

echo "==> Deploy main"
echo "    GCP_PROJECT_ID=${GCP_PROJECT_ID} REGION=${REGION} READON_DEPLOY_ENV=${READON_DEPLOY_ENV}"
echo "    service=${MAIN_RUN_SERVICE_NAME} service_account=${MAIN_SA_EMAIL}"
echo "    bucket=${READON_STORAGE_BUCKET} database=${READON_DATABASE_NAME}"
echo "    Image: ${IMAGE_URI}"

if [[ "${SKIP_BUILD:-false}" != "true" ]]; then
  bash "${script_dir}/build-image.sh" "${DOCKERFILE_PATH}" "${IMAGE_URI}"
else
  echo "Skipping build-image (SKIP_BUILD=true)."
fi

gcloud beta run deploy "${MAIN_RUN_SERVICE_NAME}" \
  --image="${IMAGE_URI}" \
  --region="${REGION}" \
  --service-account="${MAIN_SA_EMAIL}" \
  --port=8080 \
  --allow-unauthenticated \
  --ingress=all \
  --add-cloudsql-instances="${CLOUDSQL_CONNECTION_NAME}" \
  --deploy-health-check \
  --liveness-probe=httpGet.path=/health,httpGet.port=8080 \
  --readiness-probe=httpGet.path=/ready,httpGet.port=8080 \
  --startup-probe=httpGet.path=/live,httpGet.port=8080 \
  --set-env-vars="^##^${ENV_VARS}" \
  --labels="app=readon,component=${MAIN_RUN_SERVICE_NAME},managed-by=ops-gcp,readon-env=${READON_DEPLOY_ENV}" \
  --quiet

echo "Done deploying ${MAIN_RUN_SERVICE_NAME}"

