export enum GenerationStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum ErrorCode {
  INVALID_REQUEST = 'INVALID_REQUEST',
  IMAGE_PROVIDER_TIMEOUT = 'IMAGE_PROVIDER_TIMEOUT',
  IMAGE_PROVIDER_UNAVAILABLE = 'IMAGE_PROVIDER_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  STORAGE_FAILURE = 'STORAGE_FAILURE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export enum ImageProvider {
  EXTERNAL_AI_PROVIDER = 'external-ai-provider',
}
